### ISSUE TITLE
可以下载编译吗

### ISSUE THREAD

**Issue by zyxiaofeng** [HHHHhgqcdxhg/bubble-danmaku#4]
我尝试

**Comment by zyxiaofeng** [comment]
npm install
npm WARN bubble-danmaku@0.0.5-alpha license should be a valid SPDX license expression

npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for windows-build-tools@5.2.2: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm ERR! notsup Valid OS:    win32
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: x64

**Comment by QriDoki** [comment]
啊这是我蠢了, 我把windows-build-tools加到依赖里去了, 把windows-build-tools从依赖里移掉就不会有这个问题了 @zyxiaofeng

**Comment by QriDoki** [comment]
另外注意一下, npm run build里, 会执行一个/scripts/afterBuild.js脚本, 那个是我针对windows写的, 编译mac版本的时候可以在package.json里, build那个脚本里把后面的执行afterBuild.js的部分去掉
